# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c9818131e080f0d3f513de03394697ed64681bc2073192b6907fc246c7041abcd8c486c12ba4cb4d4da6034ea25be82150e838bf17cb5c32618a6a7e48196c7d

test:
  secret_key_base: 7af5a887a490a5b3706399e9064a78e5735dc2584bad3952dee2566d78c6807da3dc0b38aa98959a8658addd035949ddf6c90fae5aa7039408566dcf65ff195a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
